### ISSUE TITLE
Module not found: Error : Can't rezolve 'nativescript-material-bottomsheet` 

### ISSUE THREAD

**Issue by alexandruantonica** [Akylas/nativescript-material-components#18] opened 2019-06-07 09:50 UTC
If I use only `nativescript-material-ripple` I got this warning. 

```
WARNING in ../node_modules/nativescript-material-core/core.js
Module not found: Error: Can't resolve 'nativescript-material-bottomsheet' in '/Users/.../myApp/node_modules/nativescript-material-core'
 @ ../node_modules/nativescript-material-core/core.js
 @ ../node_modules/nativescript-material-ripple/ripple.js
 @ ./main.ts
```

**Comment by farfromrefug** [comment] 2019-06-07 11:56
@alexandruantonica indeed you get this warning. Will be removed in the next releases.

**Comment by farfromrefug** [comment] 2019-06-11 08:09
@alexandruantonica  should be fixed in 2.2.16

**Comment by alexandruantonica** [comment] 2019-07-12 20:33
@farfromrefug Thanks for the change :) It solved the warning, indeed. I'm using `2.2.17` and no warning message from `material-ripple` but...  😄 
```
WARNING in ../node_modules/nativescript-material-core/core.js
Module not found: Error: Can't resolve 'nativescript-material-bottomsheet' in '/Users/alexa/Workspace/Tappter/tappter-app/node_modules/nativescript-material-core'
 @ ../node_modules/nativescript-material-core/core.js
 @ ../node_modules/nativescript-material-button/button.js
 @ ./main.ts
```
I forgot to mention I use the `nativescript-material-button` as well.

**Comment by henrychavez** [comment] 2019-07-12 20:44
Hi @alexandruantonica indeed the problem is that the button has `nativescript-material-core` as a dependency for theming purposes and right now the `nativescript-material-core` has a function called `install()` that requires de `nativescript-material-bottomsheet` module, as a workaround I suggest you install the `nativescript-material-bottomsheet` module to avoid that warning if you are getting problems in your app. Until a fix is released 😄

**Comment by alexandruantonica** [comment] 2019-07-12 20:46
@henrychavez Cool. I will keep it like that, it's just a warning. 
Your idea will make the size of my app a bit bigger and it is a bigger problem than just a warning. 

Thanks ;)

**Comment by shiv19** [comment] 2019-07-12 21:13
#31

**Comment by farfromrefug** [comment] 2019-07-20 12:10
@alexandruantonica can we close this?

**Comment by alexandruantonica** [comment] 2019-07-20 12:12
@farfromrefug Sure.

**Closed** 2019-07-20 12:12 UTC
