### ISSUE TITLE
Bottom sheet visuals ara bad and crashes on  iOS

### ISSUE THREAD

**Issue by darkyelox** [Akylas/nativescript-material-components#57] opened 2019-09-21 19:57 UTC
Runs great on Android but when tested on iOS i have three problems:
* Setting a background makes the view have an up and bottom white space (doesn't happen on Android)
* When opening the view inmediatelly when the view is loaded and trying to close it gives the error:
  `Trying to hide bottom-sheet view but no parent with viewController specified.` and the app closes
* When is selected and element from the list and is called `closeCallback` the same error appears but the app doesn't crash, instead, the bottomsheet is not closed and the user haves to close doing a tap outside.

### Which platform(s) does your issue occur on?
- iOS simulator version 12.2

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1
- Cross-platform modules: 6.1.1
- Runtime(s): Android -> 6.1.1,  iOS -> 6.1.0
- Plugin:
```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "class-transformer": "^0.1.9",
    "class-validator": "^0.8.5",
    "clone": "^2.1.1",
    "fast-deep-equal": "^2.0.1",
    "filename-regex": "^2.0.1",
    "human-format": "^0.10.1",
    "libphonenumber-js": "^1.4.6",
    "lodash.difference": "^4.5.0",
    "lodash.has": "^4.5.2",
    "lodash.isnil": "^4.0.0",
    "lodash.last": "^3.0.0",
    "lodash.merge": "^4.6.1",
    "lodash.mergewith": "^4.6.1",
    "lodash.padstart": "^4.6.1",
    "lodash.random": "^3.2.0",
    "lodash.remove": "^4.7.0",
    "lodash.values": "^4.3.0",
    "moment": "^2.24.0",
    "moment-duration-format": "^2.2.2",
    "nativescript-advanced-webview": "^3.0.2",
    "nativescript-angular": "^8.2.1",
    "nativescript-audio": "file:../plugins/nativescript-audio/publish/package/nativescript-audio-5.0.1.tgz",
    "nativescript-bottom-navigation": "^1.3.0",
    "nativescript-calendar": "^2.0.1",
    "nativescript-datetimepicker": "^1.2.1",
    "nativescript-downloader": "file:../plugins/nativescript-downloader/publish/package/nativescript-downloader-2.1.4.tgz",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-email": "^1.5.3",
    "nativescript-fancyalert": "^3.0.6",
    "nativescript-feedback": "^1.3.5",
    "nativescript-http-formdata": "^1.6.0",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-imagecropper": "^1.0.5",
    "nativescript-imagepicker": "^6.1.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.4.0",
    "nativescript-local-notifications": "^3.1.2",
    "nativescript-localize": "^4.1.1",
    "nativescript-masked-text-field": "^4.0.1",
    "nativescript-material-bottomsheet": "^2.3.24",
    "nativescript-ng-ripple": "^2.0.1",
    "nativescript-orientation": "^2.2.1",
    "nativescript-pager": "^11.0.9",
    "nativescript-permissions": "^1.2.3",
    "nativescript-plugin-firebase": "9.0.2",
    "nativescript-purchase": "^2.0.11",
    "nativescript-rater": "^2.1.0",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-sqlite-commercial": "file:nativescript-sqlite-commercial-1.3.2.tgz",
    "nativescript-star-ratings": "file:../plugins/nativescript-star-ratings/publish/package/nativescript-star-ratings-1.0.0.tgz",
    "nativescript-telephony": "^1.0.4",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-tslib": "^1.9.1-r1",
    "nativescript-ui-autocomplete": "5.0.0",
    "nativescript-ui-calendar": "5.0.0",
    "nativescript-ui-chart": "5.0.0",
    "nativescript-ui-gauge": "5.0.0",
    "nativescript-ui-listview": "7.0.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "ngx-custom-validators": "^6.1.0",
    "ngx-moment": "^3.1.0",
    "pauseable": "^0.3.1",
    "reflect-metadata": "~0.1.10",
    "rx-singleton-lock": "^1.1.1",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.1.1",
    "typeorm": "file:../../../../typescript/typeorm/build/package",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "~0.5.0",
    "@ngtools/webpack": "~8.2.0",
    "@types/node": "^11.13.0",
    "csv": "^5.1.1",
    "decompress": "^4.2.0",
    "download": "^7.1.0",
    "nativescript-dev-webpack": "^1.2.0",
    "nativescript-environments": "file:../plugins/nativescript-environments/publish/package/nativescript-environments-1.0.0.tgz",
    "node-sass": "4.12.0",
    "promisepipe": "^3.0.0",
    "sqlite": "^3.0.0",
    "sqlite3": "^4.0.6",
    "tns-platform-declarations": "6.0.1",
    "ts-loader": "^5.3.3",
    "typescript": "~3.5.3",
    "unzipper": "^0.9.8"
  }

```

### Please, tell us how to recreate the issue in as much detail as possible. 
Using the same code as the demo-ng folder.

**Comment by bradmartin** [comment] 2019-09-24 17:39
Also running into this: https://github.com/Akylas/nativescript-material-components/blob/master/src/bottomsheet/bottomsheet.ios.ts#L227 on iOS with an Angular app.

Still trying to determine best approach to work around.

**Comment by bradmartin** [comment] 2019-09-24 18:01
Took me a few to find the old code I had where I worked with viewcontrollers and dismissing things.

So with NS I think the angular service can drop the requirement to pass in the `ViewContainerRef` in the show bottom sheet options.

The plugin itself can grab the current viewcontroller by using the `frame` module (even in angular).

```typescript

import { topmost } from 'tns-core-modules/ui/frame';

hideNativeBottomSheet() {
  const viewController = topmost().currentPage.ios;
const parentController = viewController;

// that's it unless you wanna dump the `parentController var` and instead use the direct `viewController var` to call the `dismissViewController...` method.
}
```

**Comment by bradmartin** [comment] 2019-09-24 18:02
@henrychavez - curious to hear your thoughts since you did a bit of the angular work I believe on this module :) 

I have that workaround in my current ng app and it's working fine to always close the bottom sheet without having the error come up.

**Comment by bradmartin** [comment] 2019-09-24 18:36
Actually, I'm wrong, there is no need for even doing that. After looking at the bottomsheet.ios file a bit more. The `viewcontroller` member of the class is already being set when the bottom sheet is shown and that `viewcontroller` instance should be what is used during `dismiss...`

I've confirmed this works and it also avoids an issue I introduced with the frame and that was it closed ALL VCs and I'm showing a bottomsheet with a modal already open so this wasn't acceptable.

**Comment by bradmartin** [comment] 2019-09-24 18:38
So just using `this.viewController` to dismiss does indeed work https://github.com/Akylas/nativescript-material-components/blob/master/src/bottomsheet/bottomsheet.ios.ts#L232 and doesn't seem to introduce any side effects within Angular app and I don't see any reason it would cause issues. Should be a simple PR.

**Comment by bradmartin** [comment] 2019-09-25 17:23
The first point here about the top/bottom being too large is linked to this line https://github.com/Akylas/nativescript-material-components/blob/master/src/bottomsheet/bottomsheet.ios.ts#L117
where the `position.top is being added to the layout height. Which adds the large empty space on top and bottom of the layout. 

Not certain on an appropriate fix yet, working on something and we'll report back.

**Comment by bradmartin** [comment] 2019-09-25 18:20
Potential solution: don't use `position.top +` when creating the `CGSizeMake()`. I'm running it with a simple layout on iPhone Xr and `position.top = 88` which is why you have the large empty space on top and bottom of the provided NS layout into the bottom sheet.

I'm going to use 
```
position.top / 2 +
        utils_1.layout.toDeviceIndependentPixels(owner.getMeasuredHeight())
```
 for the height of the CGSizeMake which reduces the empty whitespace on top and bottom of the actual layout by half which is more visually appealing.

Screenshots below show result of dividing `position.top / 2`

![Simulator Screen Shot - iPhone Xʀ - 2019-09-25 at 13 20 07](https://user-images.githubusercontent.com/6006148/65628540-3a23ef00-df97-11e9-80e9-0130c8f0e3d7.png)
![Simulator Screen Shot - iPhone 6 - 2019-09-25 at 13 20 08](https://user-images.githubusercontent.com/6006148/65628541-3a23ef00-df97-11e9-9c75-18c91304b338.png)

**Comment by bradmartin** [comment] 2019-09-25 18:24
This screenshot is with the current code only using `position.top +` running on iPhone Xr:

![Simulator Screen Shot - iPhone Xʀ - 2019-09-25 at 13 24 21](https://user-images.githubusercontent.com/6006148/65628832-d9e17d00-df97-11e9-9b81-bea1329bc2dd.png)

**Comment by farfromrefug** [comment] 2019-09-26 07:25
@bradmartin will look into that. But as look back at that code. Might it be that we need to use position.bottom and not position.top? I mean it is to get the bottom safe area handle if i remember correctly.
Will look at it right away

**Comment by bradmartin** [comment] 2019-09-26 11:06
Yeah you might be right. I forget what bottom was returning. I played around with different values and approaches but I never could get the top empty space removed, it looks better on devices without safe area. The iPhone XR in testing always had a good top empty space 😞 that I couldn't figure out how to accommodate for.

**Comment by farfromrefug** [comment] 2019-09-26 11:06
@darkyelox found the reason for the crash. It is fixed and i will release it soon.
@bradmartin found the reason for the layout issue. The issue is that the ViewController (BottomSheetUILayoutViewController) is applied a safearea as a normal view controller. Thus the difference on different iphones. What we want is to remove the top safearea layout constraint. 
I know how to fix it. Working on it right now

**Comment by farfromrefug** [comment] 2019-09-26 11:21
@bradmartin fixed! Release soon
<img width="799" alt="Screen Shot 2019-09-26 at 13 20 36" src="https://user-images.githubusercontent.com/655344/65684680-7e2ef680-e060-11e9-9729-3ab0823627c4.png">

**Comment by bradmartin** [comment] 2019-09-26 12:19
Nice. Did you see my notes about the crash also? I ran into that quite a bit and it seems that the viewContainerRef might not be entirely necessary to pass. Curious what you found there also. Thanks again for helping with this.

**Comment by farfromrefug** [comment] 2019-09-26 12:23
@bradmartin yes i saw but i dont use Angular at all :s 
I did fix the error with ```Trying to hide bottom-sheet view but no parent with viewController specified``` by using ```ios.getParentWithViewController```. That might be a fix for your comment in a sense.

**Comment by bradmartin** [comment] 2019-09-26 13:36
Gotcha. I am gonna play around with next release without that option and see if behavior is fine and let you know if we can drop that as part of the options.

**Comment by farfromrefug** [comment] 2019-09-26 14:03
@bradmartin @darkyelox the new release is out

**Comment by bradmartin** [comment] 2019-09-27 19:17
@farfromrefug can confirm this fixed the issues on iOS 👍 

I'm going to open a new issue for a small feature request that I'm encountering with the changes here regarding the layout for top/bottom that was changed

**Comment by farfromrefug** [comment] 2019-09-28 07:50
@darkyelox  Can i let you  close this one ?

**Comment by darkyelox** [comment] 2019-10-02 01:39
@farfromrefug yep, with the last version now everything works, tested on Android and iOS.

**Closed** 2019-10-02 07:53 UTC

**Comment by Firetrip** [comment] 2020-02-19 10:11
hello,

i am running nativescript 6.4 and the error with the additional whitespace seems to occur again on the iphone 11 pro max..

![image](https://user-images.githubusercontent.com/6661557/74824505-8e45bc00-5308-11ea-8c57-b27cec87b404.png)

**Comment by farfromrefug** [comment] 2020-02-19 10:22
@Firetrip we are going to need more info ...
What versions are you using? 
A sample repo please?

**Comment by Firetrip** [comment] 2020-02-19 10:39
Hey @farfromrefug ,

sorry :)
I am using version 3.1.6


this are my dependencies: 
```

"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@mapbox/polyline": "^1.1.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@owen-it/nativescript-uuid": "0.0.4",
    "@turf/turf": "^5.1.6",
    "@types/node": "^12.7.11",
    "class-validator": "^0.11.0",
    "libphonenumber-js": "^1.7.27",
    "nativescript-android-utils": "^1.0.2",
    "nativescript-angular": "^8.21.0",
    "nativescript-appavailability": "^1.3.2",
    "nativescript-camera": "^4.5.0",
    "nativescript-cardview": "^3.2.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-cfalert-dialog": "^1.0.15",
    "nativescript-fancyalert": "^3.0.9",
    "nativescript-feedback": "^1.3.12",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-google-maps-sdk": "^2.8.0",
    "nativescript-imagecropper": "^1.0.7",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-local-notifications": "^4.0.1",
    "nativescript-localize": "^4.2.0",
    "nativescript-material-bottomsheet": "^3.1.6",
    "nativescript-menu": "^1.1.3",
    "nativescript-ng-ripple": "^2.0.1",
    "nativescript-permissions": "^1.3.8",
    "nativescript-plugin-firebase": "^10.1.1",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-windowed-modal": "^6.0.0",
    "pure-uuid": "^1.5.7",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.4.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "^8.3.21",
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^0.7.1",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "^1.5.0",
    "node-sass": "^4.7.1",
    "tns-platform-declarations": "^6.1.1",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
```

And I am opening the bottomsheet like this
```
import { BottomSheetOptions, BottomSheetService } from 'nativescript-material-bottomsheet/angular';
.
.
.

const options: BottomSheetOptions = {
      viewContainerRef: this.viewContainerRef,
      context: {
            createTripModi: [
                    {
                        id: 1,
                        name: 'one_way'
                    },
                    {
                        id: 2,
                        name: 'two_way'
                    }
                ]
            }
        };
this.bottomSheet.show(CreateTripModusDeciderComponent, options).subscribe((result) => {
            // DO STUFF
});
```

and this is the template for my component. which i basically copied from the example.
```
<ListView row="0" [items]="createTripModi" (itemTap)="onTap($event)" separatorColor="white" class="list-group">
    <ng-template let-modus="item">
        <Label class="list-group-item" text="{{modus?.name | L}}"></Label>
    </ng-template>
</ListView>

```

**Comment by Firetrip** [comment] 2020-02-19 11:47
Here is also a give from the issue.

![bug_bottomsheet](https://user-images.githubusercontent.com/6661557/74831653-f2bb4800-5315-11ea-8813-5d1aa0580689.gif)

**Comment by Firetrip** [comment] 2020-02-19 12:28
I think i found a fix. 
i did some console logging in your plugin, when the layoutView method of bottomsheet.ios.js runs.

![image](https://user-images.githubusercontent.com/6661557/74834105-1208a400-531b-11ea-89aa-2ecf7b9cc7a4.png)
what you can see, is that the value of `safeAreaPositionTop` suddenly changes. (the log is from just a single `.show` call and I am not sure, why there happen multiple layoutView calls. 

I found that if i simply substract the safeAreaPositionTop value when calling:
`        view_1.View.layoutChild(null, owner, marginLeft, top, width + marginLeft, height + top);
`
fixes the issue.

I hotfixed it with the following piece (starting at line 102 in bottomsheet.ios.js):
```
if (!this.ignoreTopSafeArea) {
    top += safeAreaPosition.top;
} else if (this.ignoreTopSafeArea && safeAreaPosition.top !== 0) {
    top -= safeAreaPosition.top;
}
```

I tested it on an iPhone 11 Pro Max and an iPhone 7 simulator. 
Maybe it is caused by the BottomNavigation element, that is the basis for my navigation (placed at the bottom of the screen). I call the BottomSheet when one of the TabStripItems of the BottomNavigation is tapped.

**Comment by farfromrefug** [comment] 2020-02-19 13:38
@Firetrip have you seen [this](https://github.com/Akylas/nativescript-material-components/blob/62cdb4a253feb5b32e2ae713dade1b59f5ca6016/src/bottomsheet/bottomsheet-common.ts#L42)? Normally everything is possible depending on what you want

**Comment by Firetrip** [comment] 2020-02-19 13:43
yeah i have seen it. setting it however has no effect .

**Comment by Firetrip** [comment] 2020-02-19 13:52
Also just a minor difference, but I work with an Angular Project, so I import my Options from /angular and not the one you sent. But except the viewContainerReference they are anyway the same :)

**Comment by JNicolasW** [comment] 2020-04-15 17:55
If someone still have problem with iOs +X and the bottom sheets are showing big gaps in top or bottom, there is a property in the bottom sheet options call:  "ignoreTopSafeArea" and "ignoreBottomSafeArea", these are set to true by default, change to false and the gaps are gone. *Affects only iOs*
